# Generated by Django 2.0.1 on 2018-02-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='challenge_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='deadline_length',
            field=models.IntegerField(blank=14, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='deadline_time',
            field=models.IntegerField(blank=2100, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='elo_sensitivity',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='member',
            name='privilege',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='core.Member'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='core.Member'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='core.Member'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='core.Member'),
        ),
    ]
