# Generated by Django 2.0.1 on 2018-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180218_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
