# Generated by Django 2.0.2 on 2018-02-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180218_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
