# Generated by Django 2.0.2 on 2018-02-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_match_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='deadline_length',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='deadline_time',
        ),
    ]
